### ISSUE TITLE
Error in function name

### ISSUE THREAD

**Issue by alexmerz** [cleverpush/cleverpush-wordpress-plugin#7]
Hi, 

there is a error when calling esc_att() -> should be esc_attr() 

 Fatal error: Uncaught Error: Call to undefined function esc_att()
in /var/www/wp-content/plugins/cleverpush/cleverpush.php on line 1359

Best
Alex

**Comment by mariusglauer** [comment]
@alexmerz Oops, thanks for the report! v1.7.2 is just being released with a fix.
